# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OESTIDigital
description: > # this means to ignore newlines until "baseurl:"
  OESTIDigital Ã© a comunidade de TI do extremo oeste de SC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oestidigital.github.io" # the base hostname & protocol for your site
github_username: oestidigital

# Build settings
markdown: kramdown
